=== jgwest/slice/SliceShared/src/META-INF/FileConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.slice.com/datatypes/FileConfiguration"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:tns="http://www.slice.com/datatypes/FileConfiguration"  jxb:version="1.0">

    <complexType name="ProductType">
		<annotation>
			<appinfo>
				<jxb:class name="ProductDTO"></jxb:class>
			</appinfo>
		</annotation>

		<all>
			<element name="Id" type="string" minOccurs="1"></element>

			<element name="PathToSourceDir" type="string"
				minOccurs="1">
			</element>

			<!--<element name="JavaSrcFsDatabasePath" type="string"
				minOccurs="0">
				</element>
				<element name="JavaSrcFsLuceneDatabasePath" type="string"
				minOccurs="0">
				</element>
			-->

			<element name="SearchWhoaCowboyFilesNumberText"
				type="string">
			</element>
			<element name="SearchWhoaCowboyFilesNumber" type="int">
			</element>
			<element name="SearchWhoaCowboyQueryTimeoutInSecs"
				type="int">
			</element>
			<element name="SearchComponentMapFile" type="string"
				minOccurs="0">
			</element>
			<element name="LogFileOutPath" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="SearchAdminEmail" type="string" maxOccurs="1"
				minOccurs="1">
			</element>

			<element name="CookieName" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="Messages" type="tns:MessagesType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="Components" type="tns:ComponentsType"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="AllowList" maxOccurs="1" minOccurs="0">
				<complexType>
					<sequence>
						<element name="Allow" type="string"
							maxOccurs="unbounded" minOccurs="1">
						</element>
					</sequence>
				</complexType>
			</element>
			<element name="SearchIndex" maxOccurs="1" minOccurs="1">
				<complexType>
					<choice maxOccurs="1" minOccurs="1">
						<element name="JavaSrc" maxOccurs="1"
							minOccurs="1">
							<complexType>
								<sequence>
									<element
										name="JavaSrcFsDatabasePath" type="string" maxOccurs="1"
										minOccurs="1">
									</element>
									<element
										name="JavaSrcFsDatabaseUrl" type="string" maxOccurs="1"
										minOccurs="0">
									</element>									
								</sequence>
							</complexType>
						</element>
						<element name="Lucene" maxOccurs="1"
							minOccurs="1">
							<complexType>
								<sequence>
									<element
										name="JavaSrcFsLuceneDatabasePath" type="string" maxOccurs="1"
										minOccurs="1">
									</element>
								</sequence>
							</complexType>
						</element>
					</choice>
				</complexType>
			</element>
			<element name="IndexerIgnoreList"
				type="tns:IndexerIgnoreListType" maxOccurs="1" minOccurs="0">
			</element>
			<element name="SearchFileTypes"
				type="tns:SearchFileTypes">
			</element>
			<element name="FileIndexerPath" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="DatabasePresharedKey" type="string" maxOccurs="1" minOccurs="0"></element>
		</all>
    </complexType>

    <element name="Config" type="tns:ConfigType"></element>
    
    <complexType name="ConfigType">
    	<annotation>
    		<appinfo>
    			<jxb:class name="ConfigDTO"></jxb:class>
    		</appinfo>
    	</annotation>

    	<sequence>
    		<element name="ConfigEntries" type="tns:ConfigEntries" minOccurs="1" maxOccurs="1"/>
    		<element name="Product" type="tns:ProductType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="version" type="decimal" use="required"></attribute>
    </complexType>


    <complexType name="MessagesType">
		<annotation>
			<appinfo>
				<jxb:class name="MessagesDTO"></jxb:class>
			</appinfo>
		</annotation>
		<all>
			<element name="PageTitle" type="string"></element>
			<element name="TopTitle" type="string"></element>
			<element name="ContentTitle" type="string"></element>
			<element name="ContentDescription" type="string"></element>

			<element name="TextToSearchFor" type="string"></element>
			<element name="SpecifyExclude" type="string"></element>
			<element name="SpecifyOnlyInclude" type="string"></element>
		</all>
    </complexType>

    <complexType name="ComponentsType">
    
    	<annotation>
			<appinfo>
				<jxb:class name="ComponentsDTO"></jxb:class>
			</appinfo>
		</annotation>
    
    	<sequence>
    		<element name="Component" maxOccurs="unbounded" minOccurs="0">
    			<complexType>
    				<attribute name="name" type="string"></attribute>
    				<attribute name="path" type="string"></attribute>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="ConfigEntries">
		<annotation>
    		<appinfo>
    			<jxb:class name="ConfigEntriesDTO"></jxb:class>
    		</appinfo>
    	</annotation>
    	<sequence>
    		<any minOccurs="0" maxOccurs="unbounded" processContents="lax"></any>
    	</sequence>
    </complexType>

    <complexType name="SearchFileTypes">
        <annotation>
			<appinfo>
				<jxb:class name="SearchFileTypesDTO"></jxb:class>
			</appinfo>
		</annotation>

    	<sequence>
    		<element name="SearchFileType" type="tns:SearchFileType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="SearchFileType">
    	<annotation>
    		<appinfo>
    			<jxb:class name="SearchFileTypeDTO"></jxb:class>
    		</appinfo>
    	</annotation>

    	<sequence>
    		<element name="SearchNameText" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="SupportedExtensionsList"
    			type="tns:string_list" maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="selectedByDefault" type="boolean" use="optional"></attribute>
    </complexType>



    <simpleType name="string_list">
	  <list itemType="string" />
	</simpleType>

    

    <complexType name="IndexerIgnoreListType">
    	<annotation>
    		<appinfo>
    			<jxb:class name="IndexerIgnoreListTypeDTO"></jxb:class>
    		</appinfo>
    	</annotation>
    
    	<sequence>
    		<element name="Ignore" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>
</schema>

=== jgwest/slice/artifacts/GettingStarted-FileConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="http://www.slice.com/datatypes/FileConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.slice.com/datatypes/FileConfiguration FileConfiguration.xsd " version="1.0">

	<!-- 
	
	Any values contained within ${}, such as ${SRC_DIR}, will be replaced as follows, where (env_var) is the internal key, eg SRC_DIR:
	1. Look for an environment variable key matching (env_var), if found, use the environment variable value.
	2. If above not found, look for a JNDI key 'slice/(env_var)', and if found use the value
	3. If above not found, look for a JVM system property (specified to the JVM as -D(env_var)=(value) ), and use that value if found.

	This gives you a variety of options on how to configure user-defined values in your configuration file: from system/liberty environment variables, 
	from the Liberty server.xml, or from system properties of he JVM.
	-->

	<ConfigEntries>
		<!-- A list of user name/password combinations -->
		<User name="test-user" password="test-password"/>
	</ConfigEntries>

	<Product>
		<!-- The name of the product, which controls the URL it can be accessed at: /SliceRS/resources/(id) -->
		<Id>test-src</Id>

		<!-- A directory on the local file system where the source files (the files being indexed) can be found -->
		<PathToSourceDir>${SRC_DIR}</PathToSourceDir>
		
		<!-- Constants which set maximum limits on the computational size of search requests -->

		<!-- Constant: User-visible text value corresponding to the value below -->
		<SearchWhoaCowboyFilesNumberText>20,000</SearchWhoaCowboyFilesNumberText>
		<!-- Constant: The maximum number of matching files we will allow, before giving up -->
		<SearchWhoaCowboyFilesNumber>20000</SearchWhoaCowboyFilesNumber>
		<!-- Constant: The maximum length of a query we will allow before giving up -->
		<SearchWhoaCowboyQueryTimeoutInSecs>120</SearchWhoaCowboyQueryTimeoutInSecs>

		<!-- Where users can contact the administrator of this application (this is used at various points in the UI) -->
		<SearchAdminEmail>admin@admin.com</SearchAdminEmail>

		<!-- The prescence of a cookie with this name will indicate the user is authorized to access the product. -->
		<CookieName>TEST-NOT-USED</CookieName>

		<!--  These values control what text is displayed in the search page user interface. -->
		<Messages>
			<PageTitle>Text Search</PageTitle>
			<TopTitle>Text Search</TopTitle>
			<ContentTitle>Text Search</ContentTitle>
			<ContentDescription>
				Search the entirety of the Java source (.java files) and metadata (.xml/.mf/.properties) for specific text. All files are pre-indexed for fast results. 
			</ContentDescription>
			
    		<TextToSearchFor>Text to search for &lt;i&gt;(for example, you can search for package or class name)&lt;/i&gt;
    		</TextToSearchFor>
    		
    		<SpecifyExclude>(Optional) Specify file/path patterns to EXCLUDE, separated by commas. No wildcards/regexp. </SpecifyExclude>
    		<SpecifyOnlyInclude>(Optional) Specify file/path patterns to ONLY INCLUDE matches for, separated by commas. No wildcards/regexp.</SpecifyOnlyInclude>			
		</Messages>


<!--  Individual directories can be designated as components. Once a component is created in the XML, you can limit your search to one or more specific components from the web UI.

For example, if all the files in the 'myapp-backend' directory are part of a "Our product backend" component, then you can use the following Component xml:

	<Component name="Our product backend" path="myapp-bakend" />

Then, if the user selects 'Restrict results to only these streams:' in the web UI, and selected 'Our product backend', then only results from the 'myapp-backend' will be displayed.
 -->
<!-- 
		<Components>
			<Component name="(user visible name)" path="(path substring)" />
		</Components>
-->

		<!-- This element specifies which directories will be indexed, and thus which directories are allowed to be viewed by the user. 
		If a directory is not included in this list, it will not be indexed, and thus cannot be searched.. 

		A directory is allowed if the value specified in the XML matches a substring in the path. -->
		<AllowList>
			<Allow>FilenameIndexer</Allow>
			<Allow>Slice</Allow>
		</AllowList>

		<SearchIndex>
			<JavaSrc>
				<!-- This is the directory where the index database will be stored. -->
				<JavaSrcFsDatabasePath>${DB_DIR}/Test/JavaDb/</JavaSrcFsDatabasePath>
				<!-- This value is currently not used -->
				<JavaSrcFsDatabaseUrl>https://localhost:9443</JavaSrcFsDatabaseUrl>
			</JavaSrc>

			<!-- You can instead use an indexer based on Apache Lucene, as an alternative to the Slice indexer above. 
			You can only have one indexer specified per product: -->

			<!-- 
			<Lucene>
				<JavaSrcFsLuceneDatabasePath>${DB_DIR}/Test/LuceneDb</JavaSrcFsLuceneDatabasePath>
			</Lucene>
			-->

		</SearchIndex>

		<!-- You can specify path substrings to ignore; any file paths that match will not be indexed (and thus excluded from search results) -->
		<IndexerIgnoreList>
			<!--
			<Ignore>(ignore any files that match this substring)</Ignore>
			-->
		</IndexerIgnoreList>


		<!-- This XML element specifies the files that will be indexed, based on the file's file extension.  -->
		<SearchFileTypes>
			<!-- 'selectedByDefault' is an optional attribute which may be specified on any of the types, and which
			controls whether the web UI defaults to that value as cheked. -->
			<SearchFileType selectedByDefault="true">
				
				<!-- The text in the UI which corresponds to this extensions list -->
				<SearchNameText>Show matches in .java files (Recommended) </SearchNameText>
				
				<!-- A list of file extensions, separated by spaces, to index. -->
				<SupportedExtensionsList>.java</SupportedExtensionsList>
			</SearchFileType>
			
			<SearchFileType>
				<SearchNameText>Show matches in .mf, .xml and .properties files </SearchNameText>
				<SupportedExtensionsList>.mf .xml .properties</SupportedExtensionsList>
			</SearchFileType>
		</SearchFileTypes>
		
		<!-- The directory of the file indexer database. -->
		<FileIndexerPath>${DB_DIR}/Test/JavaDb/</FileIndexerPath>

	</Product>
	
	<!-- You can specify additional products here -->
	<!-- 
	<Product>
		(...)
	</Product>
	-->

</Config>

=== jgwest/slice/artifacts/Test-FileConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="http://www.slice.com/datatypes/FileConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.slice.com/datatypes/FileConfiguration FileConfiguration.xsd " version="1.0">

	<ConfigEntries>
		<User name="test-user" password="test-password"/>
	</ConfigEntries>

	<Product>
		<Id>test-src</Id>
		<PathToSourceDir>${NODE_ROOT}/Test/JavaSrc</PathToSourceDir>
		
		<SearchWhoaCowboyFilesNumberText>20,000</SearchWhoaCowboyFilesNumberText>
		<SearchWhoaCowboyFilesNumber>20000</SearchWhoaCowboyFilesNumber>
		<SearchWhoaCowboyQueryTimeoutInSecs>120</SearchWhoaCowboyQueryTimeoutInSecs>

		<SearchAdminEmail>admin@admin.com</SearchAdminEmail>

		<CookieName>TEST-NOT-USED</CookieName>

		<Messages>
			<PageTitle>Test Plug-in Text Search</PageTitle>
			<TopTitle>Test Plug-in Text Search</TopTitle>
			<ContentTitle>Test Plug-in Text Search</ContentTitle>
			<ContentDescription>
				Search the entirety of the Java source (.java files) and metadata (.xml/.mf/.properties/.map) for specific text. All files are pre-indexed for fast results. 
			</ContentDescription>
			
    		<TextToSearchFor>Text to search for &lt;i&gt;(for example, you can search for package or class name)&lt;/i&gt;
    		</TextToSearchFor>
    		
    		<SpecifyExclude>(Optional) Specify file/path patterns to EXCLUDE, separated by commas. No wildcards/regexp. </SpecifyExclude>
    		<SpecifyOnlyInclude>(Optional) Specify file/path patterns to ONLY INCLUDE matches for, separated by commas. No wildcards/regexp.</SpecifyOnlyInclude>			
		</Messages>


<!--
		<Components>
		</Components>
-->

		<AllowList>
			<Allow>FilenameIndexer</Allow>
			<Allow>Slice</Allow>
		</AllowList>

		<SearchIndex>
			<JavaSrc>
				<JavaSrcFsDatabasePath>${NODE_ROOT}/Test/JavaDb/</JavaSrcFsDatabasePath>
				<JavaSrcFsDatabaseUrl>https://localhost:9443</JavaSrcFsDatabaseUrl>
			</JavaSrc>
		</SearchIndex>

		<IndexerIgnoreList>
		</IndexerIgnoreList>


		<SearchFileTypes>
			<SearchFileType selectedByDefault="true">
				<SearchNameText>Show matches in .java files (Recommended) </SearchNameText>
				<SupportedExtensionsList>.java</SupportedExtensionsList>
			</SearchFileType>			
			<SearchFileType>
				<SearchNameText>Show matches in .mf, .xml, .properties, .inf, and .map files </SearchNameText>
				<SupportedExtensionsList>.mf .xml .properties .inf .map</SupportedExtensionsList>
			</SearchFileType>
		</SearchFileTypes>
		
		<FileIndexerPath>${NODE_ROOT}/Test/JavaDb/</FileIndexerPath>

		<DatabasePresharedKey>s923d72la90sJ78t7HJod8d8KQ2L9d0qD6522UIdisaiA97d</DatabasePresharedKey>

	</Product>


	<Product>
		<Id>test-src-lucene</Id>
		<PathToSourceDir>${NODE_ROOT}/Test/JavaSrc</PathToSourceDir>
		
		<SearchWhoaCowboyFilesNumberText>20,000</SearchWhoaCowboyFilesNumberText>
		<SearchWhoaCowboyFilesNumber>20000</SearchWhoaCowboyFilesNumber>
		<SearchWhoaCowboyQueryTimeoutInSecs>120</SearchWhoaCowboyQueryTimeoutInSecs>

		<SearchAdminEmail>admin@admin.com</SearchAdminEmail>

		<CookieName>TEST-NOT-USED</CookieName>

		<Messages>
			<PageTitle>Test Plug-in Text Search</PageTitle>
			<TopTitle>Test Plug-in Text Search</TopTitle>
			<ContentTitle>Test Plug-in Text Search</ContentTitle>
			<ContentDescription>
				Search the entirety of the Java source (.java files) and metadata (.xml/.mf/.properties/.map) for specific text. All files are pre-indexed for fast results. 
			</ContentDescription>
			
    		<TextToSearchFor>Text to search for &lt;i&gt;(for example, you can search for package or class name)&lt;/i&gt;
    		</TextToSearchFor>
    		
    		<SpecifyExclude>(Optional) Specify file/path patterns to EXCLUDE, separated by commas. No wildcards/regexp. </SpecifyExclude>
    		<SpecifyOnlyInclude>(Optional) Specify file/path patterns to ONLY INCLUDE matches for, separated by commas. No wildcards/regexp.</SpecifyOnlyInclude>			
		</Messages>

		<AllowList>
			<Allow>FilenameIndexer</Allow>
			<Allow>Slice</Allow>
		</AllowList>

		<SearchIndex>
			<Lucene>
				<JavaSrcFsLuceneDatabasePath>${NODE_ROOT}/Test/LuceneDb</JavaSrcFsLuceneDatabasePath>
			</Lucene>
		</SearchIndex>

		<IndexerIgnoreList>
		</IndexerIgnoreList>


		<SearchFileTypes>
			<SearchFileType selectedByDefault="true">
				<SearchNameText>Show matches in .java files (Recommended) </SearchNameText>
				<SupportedExtensionsList>.java</SupportedExtensionsList>
			</SearchFileType>			
			<SearchFileType>
				<SearchNameText>Show matches in .mf, .xml, .properties, .inf, and .map files </SearchNameText>
				<SupportedExtensionsList>.mf .xml .properties .inf .map</SupportedExtensionsList>
			</SearchFileType>
		</SearchFileTypes>
		
		<FileIndexerPath>${NODE_ROOT}/Test/LuceneDb/</FileIndexerPath>

		<DatabasePresharedKey>s923d72la90sJ78t7HJod8d8KQ2L9d0qD6522UIdisaiA97d</DatabasePresharedKey>

	</Product>


</Config>
